// src/lib/content/metadata.ts
//
// OLX Metadata Schema - defines and validates metadata from YAML frontmatter comments
//
// Metadata is specified in the first comment before the root element using YAML frontmatter:
//
// <!--
// ---
// description: A brief description of this activity
// author: Content Creator Name
// tags:
//   - psychology
//   - assessment
// category: psychology
// ---
// -->
// <Vertical id="my_activity">
//   ...
// </Vertical>
//
// The schema uses Zod for validation and provides type-safe access to metadata fields.
//

import { z } from 'zod';

/**
 * Schema for OLX file metadata
 *
 * Currently supports:
 * - description: Brief text description of the activity/content
 */
// BCP 47 language tag validator using Intl API
const languageTagSchema = z.string().refine(
  (value) => {
    try {
      Intl.getCanonicalLocales(value);
      return true;
    } catch {
      return false;
    }
  },
  { message: "Invalid BCP 47 language tag" }
);

export const OLXMetadataSchema = z.object({
  description: z.string().optional(),
  category: z.string().optional(),
  lang: languageTagSchema.optional(),  // BCP 47 language tag (e.g., 'en-Latn-US', 'ar-Arab-SA')

  // Content provenance and generation status.
  //
  // Absent on human-authored files. Present on machine-generated content:
  //   generated:
  //     method: machineTranslated   # LLM translation of another OLX file
  //     source_file: foo.olx        # file that was translated
  //     source_version: a34a12      # hash of source at translation time
  //
  //   generated:
  //     method: build               # generated by a build step (e.g., JSON → OLX)
  //     source_file: questions.json
  //
  // Heuristics derive behavior from method:
  //   - Content tier: !!generated → bestEffort
  //   - Variant preference: prefer !generated (human-authored)
  //   - Translation chain: method === 'machineTranslated' → follow source_file back to original
  //   - clean-translations: method === 'machineTranslated' → safe to delete
  generated: z.object({
    method: z.enum(['machineTranslated', 'build']),
    source_file: z.string().optional(),    // source file (e.g., 'mult.olx', 'questions.json')
    source_version: z.string().optional(), // hash of source at generation time
  }).optional(),

  // Potential future fields - uncomment and implement as needed:

  // commitAuthor[s]: z.string().optional(),
  // contributors: z.array(z.object({
  //   name: z.string(),
  //   role: z.string().optional()
  // })).optional(),

  // tags: z.array(z.string()).optional(),
  // namespace: z.string().optional(),
  // modified: z.string().datetime().optional(),

  // This might be a link to the parent objects, a git hash, a
  // human-friendly version number, some combination, or something
  // else
  // version: z.string().optional(),
})

export type OLXMetadata = z.infer<typeof OLXMetadataSchema>;
