// src/lib/types.ts

// Storage API: Grabbing OLX files from disk
export interface FileProvenance {
  type: 'file';
  path: string;
  [key: string]: any;
}

export interface GenericProvenance {
  type: string;
  path?: string;
  [key: string]: any;
}

/** A URI referencing the origin of a block
  * TODO: This should be a branded or tagged type:
  *   type ProvenanceURI = string & { __brand: "ProvenanceURI" };
  * Then we use this as:
  *   const uri = "file://content/foo.olx" as ProvenanceURI;
  * And it stops being interchangeable with strings.
*/
export type ProvenanceURI = string;

// TODO: Add similar tagged types for things like Block ID, etc.

/** Primary representation for provenance references */
export type Provenance = ProvenanceURI[];

/** Structured representation used in debug output */
export type ProvenanceStruct = FileProvenance | GenericProvenance;
export type ProvenanceEntry = ProvenanceURI | ProvenanceStruct;

// Fields API
export interface FieldInfo {
  type: 'field';
  name: string;
  event: string;
  scope: import('./state/scopes').Scope;
}

export interface FieldInfoByField { [name: string]: FieldInfo; }
export interface FieldInfoByEvent { [event: string]: FieldInfo; }

export interface Fields {
  fieldInfoByField: FieldInfoByField;
  fieldInfoByEvent: FieldInfoByEvent;
}

// Blocks
// Blueprint: How we declare / register them.
export interface BlockBlueprint {
  name?: string;
  namespace: string;
  component?: React.ComponentType<any>;
  action?: Function;
  isGrader?: boolean;
  parser?: Function;
  staticKids?: Function;
  reducers?: Function[];
  fields?: Fields;
  getValue?: Function;
  extraDebug?: React.ComponentType<any>;
  description?: string;
}

// Blocks don't pass in the namespace; that's added by the partial
type BlockBlueprintReg = Omit<BlockBlueprint, "namespace">;

// Blueprints get processed into a block
export interface Block {
  component: React.ComponentType<any>;
  _isBlock: true;
  action?: Function;
  parser?: Function;
  staticKids?: Function;
  reducers: Function[];
  getValue?: Function;
  fields: FieldInfoByField;
  OLXName: string;
  description?: string;
  namespace: string;
  blueprint: BlockBlueprint;
}

export interface ComponentMap {
  [tag: string]: Block;
}

// A list of kids can have any of these; renderedCompiledChildren should handle all of these.
// TODO: These should probably all be of type kidEntry, and the current type should move under a different key.
export type BlueprintKidEntry =
  | { type: 'block'; id: string }
  | { type: 'text'; text: string }
  | { type: 'xml'; xml: string }
  | { type: 'cdata'; value: string }
  | { type: 'html'; tag: string; attributes: any; kids: BlueprintKidEntry[] }
  | { type: 'node'; rawParsed: any };

// TODO: Rename to indicate the type of node. This is a _dynamic_ node, as generated by render.
export interface NodeInfo {
  node: any; // TODO: This should be _parsed_ node entry -- e.g. the result of loadContentTree. We should declare a type for this. I suspect it should always have id, tag, attribute, provenance, rawParsed, and kids.
  renderedKids: Record<string, NodeInfo>;
  parent?: NodeInfo;
  blueprint: BlockBlueprint;
}

export interface PropType {
  id: string;
  kids: BlueprintKidEntry[];
  idMap: Record<string, any>; // TODO: This should be a real type, mapping ideas to the "result of loadContentTree" type mentioned above. This might involve cleaning up a few parsers to be format-compliant.
  blueprint: BlockBlueprint;
  fields: FieldInfoByField;
  nodeInfo: NodeInfo;
  componentMap: ComponentMap;
  [key: string]: any;
}
