#!/usr/bin/env node
// src/scripts/clean-translations.ts
//
// Remove all autogenerated translation files from the content directory.
//
// Loads the content store, finds every variant with autogenerated === true,
// resolves its source file via the content store's provenance lookup,
// and deletes via the storage provider (which enforces path safety).
//
// Usage:
//   npm run clean-translations          # dry run (default)
//   npm run clean-translations -- --rm  # actually delete files

import { syncContentFromStorage, getSourceFile } from '../lib/content/syncContentFromStorage';
import { FileStorageProvider } from '../lib/lofs/providers/file';
import path from 'path';
import type { IdMap, OlxJson, ContentVariant } from '../lib/types';

const contentDir = path.resolve(process.env.OLX_CONTENT_DIR || './content');
const dryRun = !process.argv.includes('--rm');

async function main() {
  const provider = new FileStorageProvider(contentDir);
  const { idMap } = await syncContentFromStorage(provider);

  // Collect provenance URIs of autogenerated files
  const filesToDelete = new Set<string>();

  for (const [blockId, variantMap] of Object.entries(idMap as IdMap)) {
    for (const [variant, olxJson] of Object.entries(variantMap) as [ContentVariant, OlxJson][]) {
      if (!olxJson.autogenerated) continue;

      const fileUri = getSourceFile(blockId, variant);
      if (!fileUri) {
        console.error(`WARNING: autogenerated variant ${blockId}/${variant} has no source file in content store`);
        continue;
      }
      filesToDelete.add(fileUri);
    }
  }

  if (filesToDelete.size === 0) {
    console.log('No autogenerated translation files found.');
    process.exit(0);
  }

  if (dryRun) {
    console.log('\n==== Dry run ====\n');
  }

  const label = dryRun ? 'would delete' : 'deleting';
  for (const fileUri of filesToDelete) {
    console.log(`  ${label}: ${provider.toRelativePath(fileUri)}`);
    if (!dryRun) {
      await provider.delete(fileUri);
    }
  }

  if (dryRun) {
    console.log(`\nTo delete these ${filesToDelete.size} file(s), run:\n`);
    console.log('  npm run clean-translations -- --rm\n');
  } else {
    console.log(`\nDeleted ${filesToDelete.size} file(s).\n`);
  }

  process.exit(0);
}

main().catch(err => {
  console.error('Fatal error:', err);
  process.exit(1);
});
