// generateBlockRegistry.js
import fs from 'fs';
import path from 'path';

const blocksDir = path.resolve(process.cwd(), 'src/components/blocks/');
const outputFile = path.resolve(process.cwd(), 'src/components/blockRegistry.js');

function isBlockFile(filename) {
  return /^[A-Z].*\.(jsx|tsx|js|ts)$/.test(filename);
}

// Optional: exclude StubBlock or any flagged files
function shouldExclude(filePath) {
  if (filePath.endsWith('StubBlock.jsx') || filePath.endsWith('StubBlock.js')) return true;

  // Example: exclude files containing a specific comment string, e.g. "NO_EXPORT"
  const content = fs.readFileSync(filePath, 'utf8');
  if (content.includes('NOT_A_BLOCK')) return true;

  // Exclude any files ending with 'Client.jsx' or 'Client.tsx'
  if (/Client\.(jsx|tsx|js|ts)$/.test(filePath)) return true;

  return false;
}

function walkDir(dir) {
  let files = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files = files.concat(walkDir(fullPath));
    } else if (entry.isFile() && isBlockFile(entry.name)) {
      if (!shouldExclude(fullPath)) {
        files.push(fullPath);
      }
    }
  }
  return files;
}

// Generate import/export lines relative to blocksDir
function generateExports(files) {
  return files.map(filePath => {
    // Compute relative path from outputFile's directory to the block file
    const relativePathRaw = './' + path.relative(path.dirname(outputFile), filePath).replace(/\\/g, '/');

    const ext = path.extname(relativePathRaw);
    const relativePath = relativePathRaw.slice(0, -ext.length); // strip extension

    const baseName = path.basename(filePath, ext);
    return `export { default as ${baseName} } from '${relativePath}';`;
  });
}

function main() {
  const files = walkDir(blocksDir);
  const exportsLines = generateExports(files);

  const header = `// THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY\n` +
                 `// npm run-script build:gen-block-registry\n\n`;

  const content = header + exportsLines.join('\n') + '\n';

  fs.writeFileSync(outputFile, content);
  console.log(`Generated blockRegistry at ${outputFile} with ${files.length} exports.`);
}

main();
