flowchart LR
settingEvent["<h1>Setting Event</h1><br/>It's getting late."]
triggeringAntecedent["<h1>Triggering Antecedent</h1><br/>Roommate tells Johnny to go to bed."]
problemBehavior["<b><h1>Problem Behavior</h1><br/>Johnny runs out of the room laughing.</b>"]
maintainingConsequence["<b><h1>Maintaining Consequence</h1><br/>Roommate chases, nags</b>"]
maintainingConsequence2["<h1>Maintaining Consequence</h1><br/>Roommate pleads and begs"]
desiredBehavior["<h1>Desired Behavior</h1><br/>Johnny goes to bed on time."]
desiredConsequence["<h1>Desired Consequence</h1><br/>Johnny falls asleep."]
replacementBehavior["<h1>Alternative Behavior</h1><br/>Johnny throws a tantrum (this is what he used to do!)"]
function["<b><h1>Escape</h1><br/>Bedtime delayed</b>"]
problemStatement["<h1>Problem Statement</h1><br/>When Johnny is told to go to bed,<br/>he runs away laughing,<br/>forcing Annie's roommate to chase or nag him.<br /><br />Before she tried positive reinforcement,<br/>it was worse: he would throw a tantrum.<br/><br />Either way, the end result is that it takes forever<br/>to get Johnny to bed."]

settingEvent --> triggeringAntecedent
desiredBehavior --> desiredConsequence
triggeringAntecedent --> desiredBehavior
triggeringAntecedent --> problemBehavior
triggeringAntecedent --> replacementBehavior
problemBehavior --> maintainingConsequence
replacementBehavior --> maintainingConsequence2
maintainingConsequence --> function
maintainingConsequence2 --> function

class settingEvent set
class triggeringAntecedent ant
class desiredBehavior desired
class problemBehavior beh
class desiredConsequence outcome
class maintainingConsequence con
class maintainingConsequence2 con
class replacementBehavior beh
class function func

classDef set fill:#f4f1e9,stroke:#ffc107,stroke-width:2px,color:#000
classDef ant fill:#fff3cd,stroke:#ffc107,stroke-width:2px,color:#000
classDef beh fill:#cfe2ff,stroke:#0d6efd,stroke-width:2px,color:#000
classDef con fill:#d1e7dd,stroke:#198754,stroke-width:2px,color:#000
classDef desired fill:#6591f5,stroke:#0a58ca,stroke-width:2px,color:#000
classDef outcome fill:#c3e6cb,stroke:#28a745,stroke-width:2px,color:#000
classDef func fill:#f8d7da,stroke:#dc3545,stroke-width:2px,color:#000
