// JS port of Python's urllib.parse.quote_plus(string, safe='@').
//
// Byte-for-byte compatible with the Python implementation so that keys
// generated by this server and by Learning Observer's auth.events.encode_id
// land at identical storage paths.
//
// Python quote_plus: letters/digits/-_.~ stay unencoded, space becomes '+',
// everything else is percent-encoded. With safe='@', '@' also stays bare.
//
// JS encodeURIComponent leaves !*'() unencoded (RFC 2396 "mark" chars), but
// Python quote_plus encodes them, so we fix those up explicitly.

/**
 * Equivalent to Python's `urllib.parse.quote_plus(s, safe='@')`.
 *
 * See auth/events.py encode_id in Learning Observer for the Python original.
 */
export function quotePlus(s: string): string {
  return encodeURIComponent(s)
    .replace(/%20/g, '+')
    .replace(/%40/g, '@')
    .replace(/!/g, '%21')
    .replace(/\*/g, '%2A')
    .replace(/'/g, '%27')
    .replace(/\(/g, '%28')
    .replace(/\)/g, '%29');
}
