// src/components/componentMap.js
import React from 'react';

import * as BlockRegistry from './blockRegistry';
import blockMetadata from './blockMetadata.json';
import createStubBlock from '@/components/blocks/utility/StubBlock';
import { MATCH_BLOCKS } from '@/lib/blocks/createGrader';
import type { OLXTag, LoBlock } from '@/lib/types';

// Merge metadata onto block objects
export const COMPONENT_MAP = Object.fromEntries(
  Object.entries(BlockRegistry).map(([name, block]) => {
    const meta = blockMetadata.blocks[name];
    if (meta) {
      Object.assign(block, meta);
    }
    return [name, block];
  })
);

// Add Match blocks auto-generated by createGrader
// These are the rule variants (e.g., StringMatch) for use inside RulesGrader
Object.entries(MATCH_BLOCKS).forEach(([tag, block]: [OLXTag, LoBlock]) => {
  COMPONENT_MAP[tag] = block;
});

// Export build metadata for debugging/cache invalidation
export const BUILD_META = blockMetadata.meta;

// Structural marker blocks - parsed by parent blocks, not rendered directly
const STUB_BLOCKS = {
  MainPane: {
    description: 'Main content area marker for SideBarPanel layout',
    internal: true,
    readme: 'src/components/blocks/utility/StubBlocks/MainPane.md'
  },
  Sidebar: {
    description: 'Sidebar content marker for SideBarPanel layout',
    internal: true,
    readme: 'src/components/blocks/utility/StubBlocks/Sidebar.md'
  }
};

Object.entries(STUB_BLOCKS).forEach(([name, options]) => {
  const block = createStubBlock(name, options);
  block.readme = options.readme;
  COMPONENT_MAP[name] = block;
});

// We will validate it here, looking for common error(s).
function assertValidComponent(component, name) {
  if (typeof component !== "object") {
    console.log("Failed to validate", name, component, typeof component, component.name);
    throw new Error(
      `Component "${name}" is invalid. This may be due to importing a "use client" component in a server context. ` +
      `Make sure all client components are only used in client files.`
    );
  }
  if (!component._isBlock) {
    throw new Error(
      `Component "${name}" does not appear to be a valid block (missing "_isBlock" flag). ` +
      `Make sure it's created with createBlock().`
    );
  }
}

// Usage:
Object.entries(COMPONENT_MAP).forEach(([name, entry]) => {
  assertValidComponent(entry, name);
});
