/**
 * GET /api/activities
 *
 * Returns a list of launchable activities with i18n-aware cards.
 * Each activity card contains all the information needed for students/teachers
 * to pick which activity to engage with.
 *
 * Response:
 * {
 *   ok: boolean,
 *   activities: {
 *     [id]: {
 *       id: string,
 *       category: string,
 *       tag: string,
 *       editPath: string,
 *       title: { [variant]: string },
 *       description: { [variant]: string },
 *       availableVariants: { [variant]: 'human' | 'auto' },
 *       provenance: string[]
 *     }
 *   }
 * }
 */

import { NextRequest } from 'next/server';
import { syncContentFromStorage } from '@/lib/content/syncContentFromStorage';
import { getEditPathFromProvenance } from '@/lib/lofs/contentPaths';
import { getBestVariantServer } from '@/lib/i18n/getBestLocale';
import type { ContentTier } from '@/lib/types';

export async function GET(request: NextRequest) {
  try {
    const { idMap } = await syncContentFromStorage();

    // Filter to launchable entries and transform to activity cards
    const activities = Object.fromEntries(
      Object.entries(idMap)
        .filter(([_, variantMap]: [string, any]) => {
          // variantMap is { 'en-Latn-US': OlxJson, 'ar-Arab-SA': OlxJson, ... }
          const availableVariants = Object.keys(variantMap);
          const bestVariant = getBestVariantServer(request, availableVariants);
          const olxJson = variantMap[bestVariant];
          return olxJson.attributes.launchable === 'true';
        })
        .map(([id, variantMap]: [string, any]) => {
          // Transform nested OlxJson structure into activity card
          const availableVariants = Object.keys(variantMap);

          // Build localized title and description
          const title: Record<string, string> = {};
          const description: Record<string, string> = {};
          const availableVariantsMap: Record<string, ContentTier> = {};

          for (const variant of availableVariants) {
            const olxJson = variantMap[variant];
            title[variant] = olxJson.attributes?.title || id;
            description[variant] = olxJson.description || '';
            // Compute tier from autogenerated flag
            availableVariantsMap[variant] = olxJson.autogenerated ? 'bestEffort' : 'supported';
          }

          // Get edit path from provenance
          const bestVariant = getBestVariantServer(request, availableVariants);
          const bestEntry = variantMap[bestVariant];
          const editPathResult = getEditPathFromProvenance(bestEntry.provenance);
          const editPath = editPathResult.valid ? editPathResult.relativePath : null;

          return [
            id,
            {
              id,
              category: bestEntry.category || 'other',
              tag: bestEntry.tag,
              editPath,
              title,
              description,
              availableVariants: availableVariantsMap,
              provenance: bestEntry.provenance
            }
          ];
        })
    );

    return Response.json({
      ok: true,
      activities
    });
  } catch (err: any) {
    console.error('Error loading activities:', err);
    return Response.json(
      {
        ok: false,
        error: err.message || 'Failed to load activities'
      },
      { status: 500 }
    );
  }
}
