// packages/shared/scripts/compile-grammars.ts
// scripts/compile-grammars.js
import { promises as fs } from 'fs';
import path from 'path';
import { glob } from 'glob';
import peggy from 'peggy';
import { GRAMMAR_DIRS } from '../lib/grammarDirs';

async function compileAllPEG() {
  const files = (await Promise.all(
    GRAMMAR_DIRS.map(dir => glob(`${dir}/**/*.pegjs`))
  )).flat();

  const extensions: string[] = [];

  for (const file of files) {
    const grammar = await fs.readFile(file, 'utf-8');

    const parsedName = path.basename(file).replace('.pegjs', '');

    // Special handling for grammars with multiple entry points
    const options = {
      output: 'source' as const,
      format: 'es' as const,
      allowedStartRules: parsedName === 'expand'
        ? ['Condition', 'Template', 'FormatTemplate']
        : undefined,
    };

    const parserSource = peggy.generate(grammar, options) as string;

    const outFile = path.join(
      path.dirname(file),
      `_${parsedName}Parser.js`
    );

    // HACK: Append grammar metadata to the compiled output so peggyParser()
    // can auto-detect which grammar a parser came from. An alternative would
    // be to pass the grammar name explicitly: peggyParser("chat", { ... }).
    // Revisit if this feels too magical.
    const metadata = [
      '',
      '// Grammar metadata (auto-generated by compile-grammars)',
      `export const _grammarName = ${JSON.stringify(parsedName)};`,
      `export const _grammarExtension = ${JSON.stringify(parsedName + 'peg')};`,
      '',
    ].join('\n');

    await fs.writeFile(outFile, parserSource + metadata);
    console.log(`✅ Compiled ${file} → ${outFile}`);

    extensions.push(`${parsedName}peg`);
  }

  const extFile = path.resolve('packages/shared/generated/pegExtensions.json');
  await fs.mkdir(path.dirname(extFile), { recursive: true });
  await fs.writeFile(extFile, JSON.stringify(extensions, null, 2));
  console.log(`✅ Wrote ${extFile}`);
}

compileAllPEG().catch(err => {
  console.error('❌ Grammar compilation failed:', err);
  process.exit(1);
});
