// packages/shared/scripts/generateBlockRegistry.js
//
// Auto-generates four output files from the block source tree:
//
//   1. blockRegistryAutogen.ts    — TypeScript imports/exports for all blocks
//   2. blockMetadataAutogen.json  — Block metadata (docs, examples, i18n, git status)
//   3. componentsAutogen.css      — Aggregated component stylesheets
//   4. blockI18nAutogen.ts        — i18next resource bundle registration
//
// Run: npm run build:gen-block-registry
//
// Pipeline:
//
// ┌──────────────┐     ┌────────────┐     ┌─────────────────┐     ┌──────────────┐
// │ Block source  │────>│  Walk &    │────>│ Discover assets │────>│ Reduce to    │
// │ directories   │     │  filter    │     │ (docs, examples,│     │ output files  │
// │               │     │            │     │  i18n, git)     │     │              │
// └──────────────┘     └────────────┘     └─────────────────┘     └──────────────┘

import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';
import { minimatch } from 'minimatch';

/**
 * ═══════════════════════════════════════════════════════════════════════════════
 * CONFIGURATION — Output paths, source directories, registry type definitions
 * ═══════════════════════════════════════════════════════════════════════════════
 */

const BLOCKS_DIR          = path.resolve(process.cwd(), 'packages/shared/components/blocks/');
const BLOCK_IGNORE_FILE   = path.join(BLOCKS_DIR, '.blockignore');

const BLOCK_REGISTRY_FILE = path.resolve(process.cwd(), 'packages/shared/components/blockRegistryAutogen.ts');
const BLOCK_METADATA_FILE = path.resolve(process.cwd(), 'packages/shared/components/blockMetadataAutogen.json');
const CSS_REGISTRY_FILE   = path.resolve(process.cwd(), 'packages/shared/styles/componentsAutogen.css');
const I18N_REGISTRY_FILE  = path.resolve(process.cwd(), 'packages/shared/lib/i18n/blockI18nAutogen.ts');

const BLOCK_FILE_HEADER = `// THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY\n// npm run build:gen-block-registry\n\n`;
const CSS_FILE_HEADER   = `/* THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY */\n/* Generated by: npm run build:gen-registry */\n/* Auto-imports all component CSS files from packages/shared/components/blocks/ */\n\n`;

// Registry types: each entry declares a file pattern to match, output paths, and
// a reducer that transforms matched files into generated output content.
// Reducers return either a string (CSS) or { registryContent, metadata } (blocks).
const registryTypes = {
  blocks: {
    filePattern: /^[A-Z].*\.(jsx|tsx|js|ts)$/,
    outputFile: BLOCK_REGISTRY_FILE,
    metadataFile: BLOCK_METADATA_FILE,
    fileHeader: BLOCK_FILE_HEADER,
    reducer: reduceBlockRegistry,
  },
  css: {
    filePattern: /\.css$/,
    excludePattern: /^_|\.module\./,
    outputFile: CSS_REGISTRY_FILE,
    fileHeader: CSS_FILE_HEADER,
    reducer: reduceCssRegistry,
  }
};

/**
 * ═══════════════════════════════════════════════════════════════════════════════
 * GIT INTEGRATION — Track file status for documentation completeness checks
 * ═══════════════════════════════════════════════════════════════════════════════
 *
 * Git status lets the block metadata report which docs/blocks are committed,
 * modified, or untracked — useful for authoring tools that flag missing docs.
 *
 * Status values: 'committed' | 'modified' | 'untracked' | null (git unavailable)
 */

// Runs `git status --porcelain` once and caches results as a Map<path, status>.
// Returns null if git is unavailable (non-repo environment, CI without git, etc.).
function getGitStatusMap() {
  try {
    const output = execSync('git status --porcelain', {
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'pipe']
    });

    const statusMap = new Map();

    for (const line of output.split('\n')) {
      if (!line.trim()) continue;

      // Porcelain format: XY filename (X=staged status, Y=unstaged status)
      const status = line.slice(0, 2);
      let filePath = line.slice(3);

      // Renamed files: "R  old -> new"
      if (filePath.includes(' -> ')) {
        filePath = filePath.split(' -> ')[1];
      }

      statusMap.set(filePath, status === '??' ? 'untracked' : 'modified');
    }

    return statusMap;
  } catch (error) {
    console.warn('Warning: Could not get git status:', error.message);
    return null;
  }
}

function getFileGitStatus(filePath, gitStatusMap) {
  if (!gitStatusMap) return null;
  return gitStatusMap.get(filePath) || 'committed';
}

// Collects git hash, branch, dirty status, and timestamp for the metadata JSON.
function collectBuildMeta() {
  const meta = {
    timestamp: new Date().toISOString()
  };

  try {
    meta.gitHash = execSync('git rev-parse HEAD', {
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'pipe']
    }).trim();

    meta.gitBranch = execSync('git rev-parse --abbrev-ref HEAD', {
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'pipe']
    }).trim();

    const status = execSync('git status --porcelain', {
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'pipe']
    }).trim();
    meta.dirty = status.length > 0;
  } catch (error) {
    // Git not available — omit git fields, keep timestamp
  }

  return meta;
}

/**
 * ═══════════════════════════════════════════════════════════════════════════════
 * FILE DISCOVERY — Walk directories, apply ignore patterns, find matching files
 * ═══════════════════════════════════════════════════════════════════════════════
 *
 * Block directory structure:
 *
 *   Flat file (simple blocks):
 *     blocks/ActionButton.js
 *
 *   Directory (blocks with assets):
 *     blocks/Chat/
 *       Chat.js          — Block definition (required, exports default block)
 *       _Chat.jsx        — React component (optional, _ prefix = not a block)
 *       Chat.md          — Documentation (optional, matches block name)
 *       Chat.olx         — Example usage (optional)
 *       ChatAdvanced.olx — Additional examples (optional, block name prefix)
 *       chat.css         — Styles (optional, auto-aggregated)
 *       chat.pegjs       — PEG grammar (optional, compiled to _chatParser.js)
 *       i18n/            — Translation resources (optional)
 *         en.json
 *         ar.json
 */

function readBlockIgnore(ignorePath) {
  if (!fs.existsSync(ignorePath)) return [];
  return fs
    .readFileSync(ignorePath, 'utf8')
    .split('\n')
    .map(line => line.trim())
    .filter(line => line && !line.startsWith('#'));
}

function shouldExclude(filePath, ignorePatterns, excludePattern) {
  const relPath = path.relative(BLOCKS_DIR, filePath).replace(/\\/g, '/');

  for (const pattern of ignorePatterns) {
    if (minimatch(relPath, pattern)) return true;
  }

  const filename = path.basename(filePath);
  if (excludePattern && excludePattern.test(filename)) return true;

  // Blocks can opt out of the registry with an inline @registry-ignore comment.
  const content = fs.readFileSync(filePath, 'utf8');
  if (content.includes('@registry-ignore')) return true;

  return false;
}

function walkDir(dir, filePattern, ignorePatterns, excludePattern) {
  let files = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files = files.concat(walkDir(fullPath, filePattern, ignorePatterns, excludePattern));
    } else if (entry.isFile() && filePattern.test(entry.name)) {
      if (!shouldExclude(fullPath, ignorePatterns, excludePattern)) {
        files.push(fullPath);
      }
    }
  }
  return files;
}

function walkDirectories(dirs, filePattern, ignorePatterns, excludePattern) {
  let files = [];
  for (const dir of dirs) {
    if (!fs.existsSync(dir)) continue;
    files = files.concat(walkDir(dir, filePattern, ignorePatterns, excludePattern));
  }
  return files;
}

/**
 * ═══════════════════════════════════════════════════════════════════════════════
 * BLOCK ASSET DISCOVERY — Docs, examples, i18n, git status for each block
 * ═══════════════════════════════════════════════════════════════════════════════
 *
 * For a block named "Chat", discovers:
 *   - docs:     Chat.md (exact match)
 *   - examples: Chat*.olx or Chat*.xml (prefix match)
 *   - includes: Chat*.includes.olx — shared fixtures reused by the block's
 *               examples via <Use ref>. Synced as docs content (same
 *               docs.Chat namespace) but NOT listed as runnable examples.
 *   - i18n:     i18n/*.json (locale code derived from filename)
 */

function discoverBlockAssets(blockFilePath, gitStatusMap) {
  const dir = path.dirname(blockFilePath);
  const blockName = path.basename(blockFilePath, path.extname(blockFilePath));
  const blockRelPath = path.relative(process.cwd(), blockFilePath).replace(/\\/g, '/');
  const i18nDir = path.join(dir, 'i18n');

  const assets = {
    docs: null,
    docsGitStatus: null,
    template: null,       // Key into examples dict (editor insert template)
    demo: null,           // Key into examples dict (docs marquee example)
    examples: {},         // Dict keyed by filename
    includes: {},         // Shared fixtures (*.includes.olx) — not examples
    i18n: {},
    blockGitStatus: getFileGitStatus(blockRelPath, gitStatusMap)
  };

  if (!fs.existsSync(dir)) return assets;

  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    // Include regular files and symlinks (symlinks to files)
    if (!entry.isFile() && !entry.isSymbolicLink()) continue;

    const entryPath = path.relative(process.cwd(), path.join(dir, entry.name)).replace(/\\/g, '/');

    if (entry.name === `${blockName}.md`) {
      assets.docs = entryPath;
      assets.docsGitStatus = getFileGitStatus(entryPath, gitStatusMap);
    }
    else if (entry.name.startsWith(blockName) && entry.name.endsWith('.includes.olx')) {
      assets.includes[entry.name] = {
        path: entryPath,
        gitStatus: getFileGitStatus(entryPath, gitStatusMap)
      };
    }
    else if (
      (entry.name.startsWith(blockName) && (entry.name.endsWith('.olx') || entry.name.endsWith('.xml')))
    ) {
      assets.examples[entry.name] = {
        path: entryPath,
        gitStatus: getFileGitStatus(entryPath, gitStatusMap)
      };
    }
  }

  // Resolve template/demo as keys into the examples dict.
  // {BlockName}.olx is the primary example (fallback for both).
  // {BlockName}.template.olx overrides the editor insert template.
  // {BlockName}.demo.olx overrides the docs marquee example.
  const primaryKey = `${blockName}.olx`;
  const fallback = primaryKey in assets.examples ? primaryKey : null;
  assets.demo = `${blockName}.demo.olx` in assets.examples ? `${blockName}.demo.olx` : fallback;
  assets.template = `${blockName}.template.olx` in assets.examples ? `${blockName}.template.olx` : fallback;

  // Scan i18n/ subdirectory for per-locale JSON resource files
  if (fs.existsSync(i18nDir) && fs.statSync(i18nDir).isDirectory()) {
    for (const i18nEntry of fs.readdirSync(i18nDir, { withFileTypes: true })) {
      if (!i18nEntry.isFile() || !i18nEntry.name.endsWith('.json')) continue;

      const locale = path.basename(i18nEntry.name, '.json');
      if (!locale) continue;

      const localeFilePath = path.relative(process.cwd(), path.join(i18nDir, i18nEntry.name)).replace(/\\/g, '/');
      assets.i18n[locale] = localeFilePath;
    }
  }

  return assets;
}

/**
 * ═══════════════════════════════════════════════════════════════════════════════
 * REDUCERS — Transform discovered files into generated output content
 * ═══════════════════════════════════════════════════════════════════════════════
 *
 * Each reducer takes a list of matched files and produces the content string
 * for its output file. The blocks reducer also produces a metadata object
 * (written separately as JSON).
 */

// --- Block registry reducer ---
// Produces TypeScript imports/exports + a metadata object with docs, examples,
// i18n paths, and git status for each block.

// Blueprints usually declare neither `component` nor `componentLoader`; the
// registry wires the conventional sibling component file (`_Name.tsx`) as a
// lazy loader here. withComponentLoader() is a no-op for blocks that declared
// their own, so blueprint declarations always win. Emitting `import()` in a
// closure is what makes one registry serve everyone: node consumers
// (parseOLX, scripts, tests) never call the loaders, so importing the
// registry no longer drags in every component's dependency tree; bundlers
// code-split each component into its own lazy chunk.
const COMPONENT_FILE_EXTS = ['.tsx', '.jsx'];

function findConventionalComponent(blockFilePath) {
  const dir = path.dirname(blockFilePath);
  const blockName = path.basename(blockFilePath, path.extname(blockFilePath));
  for (const ext of COMPONENT_FILE_EXTS) {
    const candidate = path.join(dir, `_${blockName}${ext}`);
    if (fs.existsSync(candidate)) return candidate;
  }
  return null;
}

function reduceBlockRegistry(files, outputFile, gitStatusMap) {
  let imports = `import { withComponentLoader } from '@/lib/blocks/loader/componentLoader';\n`;
  const loaderWirings = [];
  const exports = [];
  const metadata = {};

  for (const filePath of files) {
    const relativePathRaw = './' + path.relative(path.dirname(outputFile), filePath).replace(/\\/g, '/');
    const ext = path.extname(relativePathRaw);
    const relativePath = relativePathRaw.slice(0, -ext.length);
    const baseName = path.basename(filePath, ext);
    const srcPath = path.relative(process.cwd(), filePath).replace(/\\/g, '/');
    const assets = discoverBlockAssets(filePath, gitStatusMap);

    imports += `import { default as ${baseName} } from '${relativePath}';\n`;
    exports.push(baseName);

    const componentFile = findConventionalComponent(filePath);
    if (componentFile) {
      const componentExt = path.extname(componentFile);
      const componentImportPath = ('./' +
        path.relative(path.dirname(outputFile), componentFile).replace(/\\/g, '/')
      ).slice(0, -componentExt.length);
      // Component files export their component as `default` or as the named
      // `_Name` convention. Emit exactly the accessor that exists — TS
      // typechecks the generated import against the real module shape.
      const componentSource = fs.readFileSync(componentFile, 'utf8');
      const hasDefault = /export\s+default\b/.test(componentSource);
      const hasNamed =
        new RegExp(`export\\s+(const|function|class)\\s+_${baseName}\\b`).test(componentSource) ||
        new RegExp(`export\\s*\\{[^}]*\\b_${baseName}\\b`).test(componentSource);
      if (hasDefault || hasNamed) {
        const accessor = hasDefault ? 'm.default' : `m._${baseName}`;
        loaderWirings.push(
          `withComponentLoader(${baseName}, () => import('${componentImportPath}').then(m => ${accessor}));`
        );
      } else {
        console.warn(
          `Warning: ${componentFile} exports neither 'default' nor '_${baseName}' — ` +
          `no componentLoader wired for ${baseName}. Export the component or ` +
          `declare component/componentLoader in the blueprint.`
        );
      }
    }

    const blockMeta = {
      source: srcPath
    };
    if (assets.blockGitStatus) {
      blockMeta.gitStatus = assets.blockGitStatus;
    }
    if (assets.docs) {
      blockMeta.readme = assets.docs;
      if (assets.docsGitStatus) {
        blockMeta.readmeGitStatus = assets.docsGitStatus;
      }
    }
    if (assets.template) blockMeta.template = assets.template;
    if (assets.demo) blockMeta.demo = assets.demo;
    if (Object.keys(assets.examples).length > 0) {
      blockMeta.examples = assets.examples;
    }
    if (Object.keys(assets.includes).length > 0) {
      blockMeta.includes = assets.includes;
    }
    if (Object.keys(assets.i18n).length > 0) {
      blockMeta.i18n = assets.i18n;
    }
    metadata[baseName] = blockMeta;
  }

  return {
    registryContent:
      imports + '\n' +
      loaderWirings.join('\n') + '\n\n' +
      `export { ${exports.join(', ')} };\n`,
    metadata
  };
}

// --- CSS registry reducer ---
// Produces @import statements aggregating all component stylesheets.

function reduceCssRegistry(files, outputFile) {
  return files.reduce((content, filePath) => {
    const relativePath = path.relative(path.dirname(outputFile), filePath).replace(/\\/g, '/');
    const baseName = path.basename(filePath, '.css');
    return content + `/* ${baseName} component styles */\n@import "./${relativePath}";\n\n`;
  }, '');
}

// --- I18n module generator ---
// Produces a TypeScript module that registers all block translation resources
// with i18next via addResourceBundle(). Each block's i18n/ directory contributes
// one import per locale, namespaced as "blocks/{BlockName}".
//
// Returns the generated file content as a string (caller writes to disk).

function blockLocaleIdentifier(blockName, locale) {
  const safeBlock = blockName.replace(/[^A-Za-z0-9_]/g, '_');
  const safeLocale = locale.replace(/[^A-Za-z0-9_]/g, '_');
  return `I18N_${safeBlock}_${safeLocale}`;
}

function relativeImportPath(fromFile, toFile) {
  let importPath = path.relative(path.dirname(fromFile), toFile).replace(/\\/g, '/');
  // Bare relative paths (no ./ prefix) are interpreted as package names by bundlers
  if (!importPath.startsWith('.')) {
    importPath = `./${importPath}`;
  }
  return importPath;
}

function generateI18nModule(allBlockMetadata = {}) {
  const entries = Object.entries(allBlockMetadata)
    .filter(([, meta]) => meta?.i18n && Object.keys(meta.i18n).length > 0)
    .sort(([a], [b]) => a.localeCompare(b));

  const imports = [];
  const registrations = [];

  // Common namespace — scan lib/i18n/common/*.json
  const commonDir = path.resolve(path.dirname(I18N_REGISTRY_FILE), 'common');
  if (fs.existsSync(commonDir) && fs.statSync(commonDir).isDirectory()) {
    const localeFiles = fs.readdirSync(commonDir)
      .filter(f => f.endsWith('.json'))
      .sort();
    for (const file of localeFiles) {
      const locale = path.basename(file, '.json');
      const importPath = relativeImportPath(
        I18N_REGISTRY_FILE,
        path.resolve(commonDir, file)
      );
      const importName = `I18N_common_${locale.replace(/[^A-Za-z0-9_]/g, '_')}`;
      imports.push(`import ${importName} from '${importPath}';`);
      registrations.push(`  i18n.addResourceBundle('${locale}', 'common', ${importName}, true, true);`);
    }
  }

  // Per-block namespaces — from block metadata
  for (const [blockName, meta] of entries) {
    const namespace = `blocks/${blockName}`;
    const locales = Object.entries(meta.i18n).sort(([a], [b]) => a.localeCompare(b));
    for (const [locale, resourceFile] of locales) {
      const importPath = relativeImportPath(
        I18N_REGISTRY_FILE,
        path.resolve(process.cwd(), resourceFile)
      );
      const importName = blockLocaleIdentifier(blockName, locale);
      imports.push(`import ${importName} from '${importPath}';`);
      registrations.push(`  i18n.addResourceBundle('${locale}', '${namespace}', ${importName}, true, true);`);
    }
  }

  const header = `// THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY\n// npm run build:gen-block-registry\n\n`;
  return [
    header,
    `import i18n from 'i18next';`,
    imports.join('\n'),
    '',
    'export function registerGeneratedBlockI18n() {',
    ...(registrations.length > 0
      ? registrations
      : ['  // No block translation resources were found in this registry run.']),
    '}',
    ''
  ].join('\n');
}

/**
 * ═══════════════════════════════════════════════════════════════════════════════
 * ORCHESTRATION — Tie the pipeline together and write output files
 * ═══════════════════════════════════════════════════════════════════════════════
 */

// Exported for use by the staleness test (staleness.test.ts), which compares
// freshly generated content against what's on disk.
export function generateAllRegistryContents() {
  const ignorePatterns = readBlockIgnore(BLOCK_IGNORE_FILE);
  const gitStatusMap = getGitStatusMap();
  const result = {};

  for (const [name, config] of Object.entries(registryTypes)) {
    const files = walkDirectories(
      [BLOCKS_DIR],
      config.filePattern,
      ignorePatterns,
      config.excludePattern
    );

    const reducerResult = config.reducer(files, config.outputFile, gitStatusMap);

    // Reducers return either a string (CSS) or { registryContent, metadata } (blocks)
    if (typeof reducerResult === 'string') {
      result[name] = {
        content: config.fileHeader + reducerResult,
        outputFile: config.outputFile,
        files
      };
    } else {
      result[name] = {
        content: config.fileHeader + reducerResult.registryContent,
        outputFile: config.outputFile,
        files,
        metadata: reducerResult.metadata,
        metadataFile: config.metadataFile
      };
    }
  }

  // Include i18n module so the staleness test covers it
  const i18nContent = generateI18nModule(result.blocks?.metadata);
  result.i18n = {
    content: i18nContent,
    outputFile: I18N_REGISTRY_FILE,
  };

  return result;
}

function writeRegistry(registryType, all) {
  const { content, outputFile, metadata, metadataFile } = all[registryType];

  const outputDir = path.dirname(outputFile);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(outputFile, content);
  console.log(`Generated ${registryType} registry at ${outputFile}.`);

  if (metadata && metadataFile) {
    const wrapped = {
      meta: collectBuildMeta(),
      blocks: metadata
    };
    const metadataContent = JSON.stringify(wrapped, null, 2) + '\n';
    fs.writeFileSync(metadataFile, metadataContent);
    console.log(`Generated ${registryType} metadata at ${metadataFile}.`);
  }
}

function main() {
  console.log('Generating all registries...');

  const all = generateAllRegistryContents();

  for (const registryType of Object.keys(all)) {
    writeRegistry(registryType, all);
  }

  console.log('All registries generated successfully.');
}

// Only run main() when executed directly, not when imported
const isDirectRun = process.argv[1]?.endsWith('generateBlockRegistry.js');
if (isDirectRun) {
  main();
}
