// packages/shared/scripts/generate-parser-registry.ts
// Generates a registry mapping PEG content extensions to their compiled parsers,
// grammar metadata (.pegjs.yaml), and content templates (.pegjs.template.{ext}).
import { promises as fs } from 'fs';
import path from 'path';
import { glob } from 'glob';
import yaml from 'js-yaml';
import { GRAMMAR_DIRS } from '../lib/grammarDirs';

const outputFile = 'packages/shared/generated/parserRegistry.ts';

async function generateParserRegistry() {
  const parserFiles = (await Promise.all(
    GRAMMAR_DIRS.map(dir => glob(`${dir}/**/_*Parser.js`))
  )).flat();

  // Use a Map to dedupe by extension (first found wins)
  const entriesMap = new Map();

  for (const parserFile of parserFiles) {
    // Extract grammar name from _fooParser.js -> foo
    const basename = path.basename(parserFile);
    const match = basename.match(/^_(.+)Parser\.js$/);
    if (!match) continue;

    const grammarName = match[1];
    const extension = `${grammarName}peg`;

    // Skip if we already have this extension
    if (entriesMap.has(extension)) continue;

    const relativePath = parserFile.startsWith('packages/shared/')
      ? '@/' + parserFile.slice('packages/shared/'.length).replace(/\.js$/, '')
      : parserFile;

    // Grammar file is in same directory as parser, named {grammarName}.pegjs
    const grammarDir = path.dirname(parserFile);
    const grammarFile = path.join(grammarDir, `${grammarName}.pegjs`);

    // Only include if the grammar source file actually exists in this directory
    // (avoids picking up duplicate compiled parsers without their source)
    try {
      await fs.access(grammarFile);
    } catch {
      continue; // Grammar file doesn't exist here, skip this parser
    }

    // Discover grammar metadata: {name}.pegjs.yaml
    let metadata: Record<string, unknown> | null = null;
    const metadataFile = path.join(grammarDir, `${grammarName}.pegjs.yaml`);
    try {
      const raw = await fs.readFile(metadataFile, 'utf-8');
      const parsed = yaml.load(raw);
      metadata = typeof parsed === 'object' && parsed !== null ? parsed as Record<string, unknown> : null;
    } catch {
      // No metadata file — that's fine
    }

    // Discover content template: .template.{ext} preferred, .preview.{ext} fallback
    let template: string | null = null;
    const templateFile = path.join(grammarDir, `${grammarName}.pegjs.template.${extension}`);
    const previewFile = path.join(grammarDir, `${grammarName}.pegjs.preview.${extension}`);
    for (const candidate of [templateFile, previewFile]) {
      try {
        template = await fs.readFile(candidate, 'utf-8');
        break;
      } catch {
        // Try next candidate
      }
    }

    entriesMap.set(extension, {
      extension,
      grammarName,
      importPath: relativePath,
      grammarDir: grammarDir.startsWith('packages/shared/') ? '@/' + grammarDir.slice('packages/shared/'.length) : grammarDir,
      template,
      metadata,
    });
  }

  const entries = Array.from(entriesMap.values());

  // Generate TypeScript registry file
  const imports = entries.map((e, i) =>
    `import * as parser_${i} from '${e.importPath}';`
  ).join('\n');

  const registryEntries = entries.map((e, i) =>
    `  '${e.extension}': parser_${i}`
  ).join(',\n');

  const extensionList = entries.map(e => `'${e.extension}'`).join(', ');

  const grammarInfoEntries = entries.map(e =>
    `  '${e.extension}': { grammarName: '${e.grammarName}', grammarDir: '${e.grammarDir}' }`
  ).join(',\n');

  // Build pegMetadata: YAML metadata from .pegjs.yaml files, with defaults
  const metadataEntries = entries
    .map(e => {
      const meta = e.metadata || {};
      const name = meta.name || e.grammarName.charAt(0).toUpperCase() + e.grammarName.slice(1);
      const creatable = meta.creatable !== undefined ? !!meta.creatable : e.template !== null;
      return `  '${e.extension}': { name: ${JSON.stringify(name)}, creatable: ${creatable} }`;
    })
    .join(',\n');

  // Build pegTemplates: content from .template.{ext} or .preview.{ext} files
  const templateEntries = entries
    .filter(e => e.template !== null)
    .map(e => `  '${e.extension}': ${JSON.stringify(e.template)}`)
    .join(',\n');

  const content = `// AUTO-GENERATED - DO NOT EDIT
// Generated by: npm run build:parser-registry
// Maps PEG content file extensions to their compiled parsers,
// grammar metadata (.pegjs.yaml), and content templates.

${imports}

export type PEGContentExtension = ${entries.map(e => `'${e.extension}'`).join(' | ')};

export const PEG_CONTENT_EXTENSIONS: readonly PEGContentExtension[] = [${extensionList}] as const;

interface PEGParser {
  parse: (input: string) => unknown;
}

interface GrammarInfo {
  grammarName: string;
  grammarDir: string;
}

export interface PEGGrammarMeta {
  name: string;
  creatable: boolean;
}

export const parserRegistry: Record<PEGContentExtension, PEGParser> = {
${registryEntries}
};

export const grammarInfo: Record<PEGContentExtension, GrammarInfo> = {
${grammarInfoEntries}
};

/** Grammar metadata from .pegjs.yaml files (with defaults for missing files). */
export const pegMetadata: Record<PEGContentExtension, PEGGrammarMeta> = {
${metadataEntries}
};

/** Content templates from .pegjs.template.{ext} or .pegjs.preview.{ext} files. */
export const pegTemplates: Partial<Record<PEGContentExtension, string>> = {
${templateEntries}
};

export function getParserForExtension(ext: string): PEGParser | undefined {
  // Case-sensitive - extensions like textSelectionpeg preserve case
  const normalized = ext.replace(/^\\./, '');
  return parserRegistry[normalized as PEGContentExtension];
}

export function isPEGContentExtension(ext: string): ext is PEGContentExtension {
  // Case-sensitive - extensions like textSelectionpeg preserve case
  const normalized = ext.replace(/^\\./, '');
  return PEG_CONTENT_EXTENSIONS.includes(normalized as PEGContentExtension);
}

/**
 * Get the path to the preview OLX file for a PEG content extension.
 * Preview files are named {grammarName}.pegjs.preview.olx
 * Returns the path relative to project root (e.g., "packages/shared/components/blocks/Chat/chat.pegjs.preview.olx")
 */
export function getPreviewPath(ext: string): string | undefined {
  // Case-sensitive - extensions like textSelectionpeg preserve case
  const normalized = ext.replace(/^\\./, '');
  const info = grammarInfo[normalized as PEGContentExtension];
  if (!info) return undefined;
  // Convert @/foo to packages/shared/foo for file system access
  const dir = info.grammarDir.replace(/^@\\//, 'packages/shared/');
  return \`\${dir}/\${info.grammarName}.pegjs.preview.olx\`;
}
`;

  await fs.mkdir(path.dirname(outputFile), { recursive: true });
  await fs.writeFile(outputFile, content);
  const withTemplates = entries.filter(e => e.template !== null);
  const withMetadata = entries.filter(e => e.metadata !== null);
  console.log(`✅ Generated ${outputFile} with ${entries.length} parsers, ${withTemplates.length} templates, ${withMetadata.length} metadata files:`);
  entries.forEach(e => {
    const flags = [
      e.template !== null ? 'template' : null,
      e.metadata !== null ? 'yaml' : null,
    ].filter(Boolean).join(', ');
    console.log(`   - ${e.extension} → ${e.importPath}${flags ? ` (${flags})` : ''}`);
  });
}

generateParserRegistry().catch(err => {
  console.error('❌ Parser registry generation failed:', err);
  process.exit(1);
});
