// src/lib/content/metadata.ts
//
// Content Metadata Schemas - shared base + format-specific extensions (OLX, chatpeg)
//
// Metadata is specified in the first comment before the root element using YAML frontmatter:
//
// <!--
// ---
// description: A brief description of this activity
// authors: Content Creator Name
// tags:
//   - psychology
//   - assessment
// category: psychology
// ---
// -->
// <Vertical id="my_activity">
//   ...
// </Vertical>
//
// The schema uses Zod for validation and provides type-safe access to metadata fields.
//

import { z } from 'zod';
import { licensed } from '@/lib/blocks/attributeSchemas';

/**
 * Schema for OLX file metadata
 *
 * Currently supports:
 * - description: Brief text description of the activity/content
 */
// BCP 47 language tag validator using Intl API
const languageTagSchema = z.string().refine(
  (value) => {
    try {
      Intl.getCanonicalLocales(value);
      return true;
    } catch {
      return false;
    }
  },
  { message: "Invalid BCP 47 language tag" }
);

/**
 * Base metadata fields shared across all content formats (OLX, chatpeg, etc.).
 * Format-specific schemas extend this with additional fields.
 */
const baseMetadataFields = {
  title: z.string().optional(),
  description: z.string().optional(),
  category: z.string().optional(),
  ...licensed,
};

export const BaseMetadataSchema = z.object(baseMetadataFields);
export type BaseMetadata = z.infer<typeof BaseMetadataSchema>;

/** Known base metadata key names, for validation/warnings in parsers. */
export const BASE_METADATA_KEYS = new Set<string>(Object.keys(baseMetadataFields));

export const OLXMetadataSchema = z.object({
  ...baseMetadataFields,
  index: z.number().optional(),
  lang: languageTagSchema.optional(),  // BCP 47 language tag (e.g., 'en-Latn-US', 'ar-Arab-SA')

  // Content provenance and generation status.
  //
  // Absent on human-authored files. Present on machine-generated content:
  //   generated:
  //     method: machineTranslated   # LLM translation of another OLX file
  //     source_file: foo.olx        # file that was translated
  //     source_version: a34a12      # hash of source at translation time
  //
  //   generated:
  //     method: build               # generated by a build step (e.g., JSON → OLX)
  //     source_file: questions.json
  //
  // Heuristics derive behavior from method:
  //   - Content tier: !!generated → bestEffort
  //   - Variant preference: prefer !generated (human-authored)
  //   - Translation chain: method === 'machineTranslated' → follow source_file back to original
  //   - clean-translations: method === 'machineTranslated' → safe to delete
  generated: z.object({
    method: z.enum(['machineTranslated', 'build']),
    source_file: z.string().optional(),    // source file (e.g., 'mult.olx', 'questions.json')
    source_version: z.string().optional(), // hash of source at generation time
  }).optional(),

  // Potential future fields - uncomment and implement as needed:

  // Authorship tracking beyond the `authors` field in `licensed`:
  // For large projects, author lists can be in the thousands. The long-term
  // direction is git-style provenance tracking (who created, forked, modified)
  // rather than flat author lists. Much of our content lives in git proper,
  // so the commit history is the canonical source. These fields are
  // breadcrumbs toward that:
  //
  // contributors: z.array(z.object({
  //   name: z.string(),
  //   role: z.string().optional()   // e.g. 'author', 'editor', 'translator'
  // })).optional(),

  // tags: z.array(z.string()).optional(),
  // namespace: z.string().optional(),
  // modified: z.string().datetime().optional(),

  // This might be a link to the parent objects, a git hash, a
  // human-friendly version number, some combination, or something
  // else
  // version: z.string().optional(),
})

export type OLXMetadata = z.infer<typeof OLXMetadataSchema>;

/**
 * Chat (chatpeg) header metadata schema.
 * Base fields + cast (speaker avatar definitions).
 */
export const ChatMetadataSchema = z.object({
  ...baseMetadataFields,
  cast: z.record(z.unknown()).optional(),
});
export type ChatMetadata = z.infer<typeof ChatMetadataSchema>;

/** Known chat metadata key names (base + chat-specific). */
export const CHAT_METADATA_KEYS = new Set<string>([
  ...BASE_METADATA_KEYS,
  'cast',
]);
